### ISSUE TITLE
no attribute 'point_cloud'

### ISSUE THREAD

**Issue by wisestruct** [ManiCM-fast/ManiCM#6]
File "train_cm.py", line 309, in run
    nobs = normalizer.normalize(batch['obs'])
  File " /ManiCM/ManiCM/diffusion_policy_3d/model/common/normalizer.py", line 68, in normalize
    return self._normalize_impl(x, forward=True)
  File " /ManiCM/ManiCM/diffusion_policy_3d/model/common/normalizer.py", line 58, in _normalize_impl
    params = self.params_dict[key]
  File "/data/conda/envs/dp3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 738, in __getitem__
    return getattr(self, attr)
  File "/data/conda/envs/dp3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ParameterDict' object has no attribute 'point_cloud'

**Comment by gao-zifeng** [comment]
You can try installing the project package in the ManiCM directory using the command `pip install -e .`.

**Comment by yrq0424** [comment]
Hello, I encountered the same issue, and I also tried “pip install -e . ”but the problem persists. How can I resolve this？
Traceback (most recent call last):
  File "train_cm.py", line 703, in <module>
    main()
  File "/home/ps/anaconda3/envs/manicm2/lib/python3.8/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/home/ps/anaconda3/envs/manicm2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/home/ps/anaconda3/envs/manicm2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/home/ps/anaconda3/envs/manicm2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/home/ps/anaconda3/envs/manicm2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/home/ps/anaconda3/envs/manicm2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/home/ps/anaconda3/envs/manicm2/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/ps/anaconda3/envs/manicm2/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/ps/anaconda3/envs/manicm2/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "train_cm.py", line 700, in main
    workspace.run()
  File "train_cm.py", line 309, in run
    nobs = normalizer.normalize(batch['obs'])
  File "/media/ps/HDD_disk/yrq/ManiCM/ManiCM/diffusion_policy_3d/model/common/normalizer.py", line 72, in normalize
    return self._normalize_impl(x, forward=True)
  File "/media/ps/HDD_disk/yrq/ManiCM/ManiCM/diffusion_policy_3d/model/common/normalizer.py", line 59, in _normalize_impl
    params = self.params_dict[key]
  File "/home/ps/anaconda3/envs/manicm2/lib/python3.8/site-packages/torch/nn/modules/container.py", line 738, in __getitem__
    return getattr(self, attr)
  File "/home/ps/anaconda3/envs/manicm2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ParameterDict' object has no attribute 'point_cloud'
